server:
    port: 9100
    contextPath: /operator/service
    session:
        timeout: 1200
    tomcat:
      accesslog:
        enabled: true
        directory: logs
shiro:
    loginUrl: /login
    filters:
        /login: anonymous
        /logout: anonymous
        /**: authorization